# Generated by Django 5.0 on 2024-01-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0002_user_isloggedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isLoggedIn',
            field=models.BooleanField(),
        ),
    ]
