# Generated by Django 5.0 on 2024-01-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0005_alter_task_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
