# Generated by Django 5.0 on 2024-01-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0006_remove_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_created',
        ),
    ]
