# Generated by Django 5.0 on 2024-01-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0008_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
